proxy:
    default:
        check: true
        timeout: 10
        tries: 3
    sites:
        gimmeproxy: # https://gimmeproxy.com/#api
            url: https://gimmeproxy.com/api/getProxy
            type: json # json/string
            check: false # override default
            timeout: 10 # override default
            tries: 3 # override default
            paths:
                ip: ip
                port: port
            filters:
                port: port # integer
                country: country # string, comma separated
                protocol: protocol # http/socks4/socks5
                https: supportsHttps # true/false
                get: get # true/false
                post: post # true/false
        pubproxy: # http://pubproxy.com/#settings
            url: http://pubproxy.com/api/proxy
            type: json # json/string
            check: false # override default
            timeout: 10 # override default
            tries: 3 # override default
            paths:
                ip: data.0.ip
                port: data.0.port
            filters:
                port: port
                country: country
                protocol: type
                https: https
                get: get
                post: post